### ISSUE TITLE
Coordinate system convention in Positions class

### ISSUE THREAD

**Issue by nschade** [manoharan-lab/holopy#10]
Dear holopy team,

The definition of theta in the Positions class (line 474 of metadata.py) appears to be consistent with conventional spherical coordinates.  However, this means that theta = 0 corresponds to the positive z axis (backscattering) and theta = pi corresponds to the negative z axis (forward scattering), the reverse of conventional scattering coordinates.  Is this correct?

Thank you,
Nick

**Comment by trinberg** [comment]
Talking with Victoria, it looks like the way to make this clear is to put in a 3d picture in the docs showing the detector, the particle, and the light coming in.

**Comment by trinberg** [comment]
We should also make link to the coordinates page from somewhere in the scattering tutorial because people thinking about scattering are the most likely to need to know about the differing z conventions.
