### ISSUE TITLE
Xarray performance

### ISSUE THREAD

**Issue by tdimiduk** [manoharan-lab/holopy#104]
It appears naive use of xarray is hurting our performance. Tests are taking longer to run (I don't have a detailed comparison yet).

I have some not scientific comparison of inference subset tempering where the new code takes over 30s  for subset tempering stages and the old code took 2-3s. 

It doesn't seem like as big of an issue on larger calculations (hopefully the fortran runtime still dominates for real hologram computations), but it is very significant at smaller subsets and on the small datasets we use for tests. 

I really don't want to have to revert the switch to xarray, but these performance losses are pretty bad. Hopefully profiling will reveal an acceptable solution.

**Comment by barkls** [comment]
It looks like we are still having performance issues with the to_spherical function. Current thinking is to have it take and return numpy arrays of coordinates rather than full xarrays.
