### ISSUE TITLE
Switch to pillow for image io 

### ISSUE THREAD

**Issue by tdimiduk** [manoharan-lab/holopy#12]
pillow (http://python-imaging.github.io/) is a fork of the Python Imaging Library that is actively developed (https://github.com/python-imaging/Pillow). It includes support for 12-bit TIFF files (https://github.com/python-imaging/Pillow/pull/416). If we switch to pillow from PIL, we can remove the dependency on tifffile.py and potentially eliminate a lot of the code in holopy/core/io/image-file-io.py.

We will need to develop unit tests for loading the 12-bit TIFF files from the Photon Focus camera and other images that have been a problem to load. If they do not load properly using pillow, we can file an issue upstream.

port of an issue by @vnmanoharan from launchpad

**Comment by barkls** [comment]
I just switched travis to installing pillow instead of PIL and everything seems to work fine.
