### ISSUE TITLE
ipython notebook, matplotlib, and inline

### ISSUE THREAD

**Issue by trinberg** [manoharan-lab/holopy#125]
In "loading and viewing a hologram" - you could make clear that an ipython notebook could be used and that if you do use ipython, you should add these lines so that you can see the image in the notebook:
```
import matplotlib
%matplotlib inline  
```

It's not a very complicated addition, but I do think that it will help some people who are not used to using ipython.

**Comment by tdimiduk** [comment]
We actually only need the %matplotlib inline line because holopy already imports matplotlib. 

More generally, we should probably have a page pointing people at jupyter and spyder and giving some quick pointers at how to use holopy with them.
