### ISSUE TITLE
Getting fortran working on a mac

### ISSUE THREAD

**Issue by tdimiduk** [manoharan-lab/holopy#128]
gfortran may put its library in a place python can't find it. If you get errors including something like

can't find /usr/local/libgfortran.3.dynlib

you can symlink them in from your install, so for example I did

sudo ln -s /usr/local/gfortran/lib/libgfortran.3.dynlib /usr/local/lib
sudo ln -s /usr/local/gfortran/lib/libquadmath.3.dynlib /usr/local/lib

**Comment by barkls** [comment]
probably conda will handle this issue for us and users don't need to worry about it.

**Comment by barkls** [comment]
This tip is now included in documentation.
