### ISSUE TITLE
HoloPy won't compile on Windows with Anaconda and gcc

### ISSUE THREAD

**Issue by vnmanoharan** [manoharan-lab/holopy#142]
I installed the MinGW gfortran from anaconda.  Also installed Visual C++ Build Tools from Microsoft.  Tried to build with
`python setup.py build_ext --inplace --fcompiler=gfortran`
Result is that f2py works, but linking fails:
```
uts_scsmfo.o : error LNK2001: unresolved external symbol ___chkstk_ms
uts_scsmfo.o : error LNK2001: unresolved external symbol _gfortran_pow_i4_i4
uts_scsmfo.o : error LNK2001: unresolved external symbol _gfortran_pow_c8_i4
SBESJY.o : error LNK2001: unresolved external symbol _gfortran_st_write
SBESJY.o : error LNK2001: unresolved external symbol _gfortran_transfer_real_write
SBESJY.o : error LNK2001: unresolved external symbol _gfortran_st_write_done
```

Also tried to build with gfortran + MinGW C compiler (instead of MSVC):
`python setup.py build_ext --inplace --compiler=mingw32`
But this fails with
```
  File "setup.py", line 101, in <module>
    package=['HoloPy'])
  File "Anaconda3\lib\site-packages\numpy\distutils\core.py", line 166, in setup
    return old_setup(**new_attr)
  File "Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "Anaconda3\lib\site-packages\numpy\distutils\command\build_ext.py", line 117, in run
    force=self.force)
  File "Anaconda3\lib\site-packages\numpy\distutils\ccompiler.py", line 596, in new_compiler
    compiler = klass(None, dry_run, force)
  File "Anaconda3\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 58, in __init__
    dry_run, force)
  File "Anaconda3\lib\distutils\cygwinccompiler.py", line 157, in __init__
    self.dll_libraries = get_msvcr()
  File "Anaconda3\lib\distutils\cygwinccompiler.py", line 86, in get_msvcr
    raise ValueError("Unknown MS Compiler version %s " % msc_ver)
ValueError: Unknown MS Compiler version 1900
```
I looked up this error and found this [stackoverflow page](http://stackoverflow.com/questions/33822554/build-fortran-extension-on-windows-with-gfortran-and-msvc) which says that the [mingwpy](http://mingwpy.github.io/mingwpy.html) project is supposed to try to solve this issue. Mingwpy is available from conda-forge, and I installed it, but I couldn't figure out how to use it to compile the extension.

There is also some information on compiling fortran extensions for windows [here](https://www.scivision.co/f2py-running-fortran-code-in-python-on-windows/).

If anyone knows how to get mingwpy to work (or if it is even at a stage where it can work), please let me know.

**Comment by ralex0** [comment]
I was able to get this working on Windows 10 with an AMD64 architecture (64-bit) processor.

Here's a quick draft of what I did. I started from a fresh user account with nothing installed.

1. Installed Anaconda, made sure it's working

2. Installed the C compiler. It's included in [Visual Studio 2015 Community](https://www.visualstudio.com/downloads/). Made sure it was working with a C helloworld.

3. From now on, make sure any command prompt window invokes the right environment conditions for compiling with VC.
On my computer, running C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat does the trick. This batch detects your architecture, then runs another batch that sets the path include the directory with the correct version of the VC compiler.

4. Installed cython and made sure it works.

5. Installed [Intel's Fortran compiler](https://software.intel.com/en-us/fortran-compilers/try-buy). I downloaded the trial version of what is called Parallel Studio XE. Made sure it was working with a Fortran helloworld.

6. Downloaded and installed the v3 holopy the ran
`python setup.py build_ext --inplace`

7. Installed these dependencies that don't come with Anaconda
```
conda install xarray dask netCDF4 bottleneck
conda install -c astropy emcee=2.2.1
```

8. Opened an ipython console where I installed holopy and try `import holopy`... It succeeds.

**Comment by barkls** [comment]
These instructions are now included in the documentation. Further discussion of Windows installation has moved to #181 so I'm closing this issue.

**Comment by vnmanoharan** [comment]
I'm reopening but I'm changing the issue title.  It's still a problem that holopy requires the intel compiler.

**Comment by vnmanoharan** [comment]
I've gotten holopy to compile with gfortran.  I don't know what changed, but it works now.  @barkls or @ralex0, could you try to compile without the Intel compiler?  My conda environment is attached.
[environment.zip](https://github.com/manoharan-lab/holopy/files/1185074/environment.zip)

**Comment by ralex0** [comment]
@vnmanoharan 
It works for me too. I complied it with Python36 using gcc via mingw.

**Comment by vnmanoharan** [comment]
@ralex0, can you put a conda package together for v3.1.1 for Windows 64-bit, using gfortran? We might need to update the dependencies.

**Comment by barkls** [comment]
As of now, it is possible to:

1) Build HoloPy from source on Windows with gcc by following the steps described by @ralex0 above.

2) Install a conda distribution of HoloPy for Windows from conda-forge, compiled with flang (see #220).
