### ISSUE TITLE
 propagate does not expect images with both negative and positive pixels

### ISSUE THREAD

**Issue by tdimiduk** [manoharan-lab/holopy#16]
Suppose
img
is an image with both negative and positive pixels.

Then
hp.show(hp.propagate(img,0.01)
gives a distinctly different result than
hp.show(hp.propagate(img - img.min(),0.01)

With autoscaling, the second result looks more similar to the un-propagated image, as desired for a propagation of a small finite distance.

**Comment by barkls** [comment]
Propagate should make all pixels non-negative and give warning if it changed any

**Comment by barkls** [comment]
I was not able to reproduce the bug. Slightly negative pixels seemed to be ok.
