### ISSUE TITLE
saving inference results doesn't work

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#171]
Something about vector xarray object cannot be written to hdf5. This is a problem in the io conversion process.

**Comment by charlieGreboval** [comment]
I run the command (hp.save('example-sampling.h5', result)) from the tutorial and I got this error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-e52fff101369> in <module>()
----> 1 hp.save('example-sampling.h5', result)

C:\Users\Charlie\Anaconda3\lib\site-packages\holopy\core\io\io.py in save(outf, obj)
    233 
    234     if hasattr(obj, '_save'):
--> 235         obj._save(outf)
    236     elif hasattr(obj, 'to_dataset'):
    237         obj=obj.copy()

C:\Users\Charlie\Anaconda3\lib\site-packages\holopy\inference\result.py in _save(self, filename)
    147             ds.to_netcdf(filename, engine='h5netcdf', group=group, mode=mode)
    148 
--> 149         write(self.end_result._serialization_ds(), 'end_result')
    150 
    151         for i, sr in enumerate(self.stage_results):

C:\Users\Charlie\Anaconda3\lib\site-packages\holopy\inference\result.py in write(ds, group, mode)
    145 
    146         def write(ds, group, mode='a'):
--> 147             ds.to_netcdf(filename, engine='h5netcdf', group=group, mode=mode)
    148 
    149         write(self.end_result._serialization_ds(), 'end_result')

C:\Users\Charlie\Anaconda3\lib\site-packages\xarray\core\dataset.py in to_netcdf(self, path, mode, format, group, engine, encoding, unlimited_dims)
    975         return to_netcdf(self, path, mode, format=format, group=group,
    976                          engine=engine, encoding=encoding,
--> 977                          unlimited_dims=unlimited_dims)
    978 
    979     def __unicode__(self):

C:\Users\Charlie\Anaconda3\lib\site-packages\xarray\backends\api.py in to_netcdf(dataset, path_or_file, mode, format, group, engine, writer, encoding, unlimited_dims)
    551     # validate Dataset keys, DataArray names, and attr keys/values
    552     _validate_dataset_names(dataset)
--> 553     _validate_attrs(dataset)
    554 
    555     try:

C:\Users\Charlie\Anaconda3\lib\site-packages\xarray\backends\api.py in _validate_attrs(dataset)
    119     for variable in dataset.variables.values():
    120         for k, v in variable.attrs.items():
--> 121             check_attr(k, v)
    122 
    123 

C:\Users\Charlie\Anaconda3\lib\site-packages\xarray\backends\api.py in check_attr(name, value)
    110                             'string, ndarray or a list/tuple of '
    111                             'numbers/strings for serialization to netCDF '
--> 112                             'files'.format(value))
    113 
    114     # Check attrs on the dataset itself

TypeError: Invalid value for attr: <xarray.DataArray (vector: 3)>
array([1, 0, 0])
Coordinates:
  * vector   (vector) <U1 'x' 'y' 'z' must be a number string, ndarray or a list/tuple of numbers/strings for serialization to netCDF files

**Comment by barkls** [comment]
Also need to write about this in the docs on the dev page.

**Comment by barkls** [comment]
Also need to fix the infer_tutorial guide.
