### ISSUE TITLE
Update adding a new inference model

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#182]
update the methods of inference model classes. Update documentation to explain how to add a new model.  @tdimiduk is working on this.

**Comment by barkls** [comment]
Hey @tdimiduk, are you going to have a chance to work on this? We are aiming to have the release wrapped up tomorrow (Friday). If you won't have time to make these changes, let me know and I will give it a stab. After our discussion at the hackathon, I'm fairly confident I could do it myself.

**Comment by tdimiduk** [comment]
I'll whip what I have into some kind of shape and submit it soon (hopefully
<1 hour). You may want to edit/improve/expand it.

**Comment by barkls** [comment]
Thanks!
