### ISSUE TITLE
Multisphere calculations return NaN

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#194]
There is a bug that has happened on Travis under a few circumstances (but never observed on an actual machine). 

Some, multisphere calculations return NaN, resulting in test failures. Other multisphere calculations run normally. This bug happened for a while when using numpy 1.11 after upgrading to xarray 0.9. It has also inconsistently occurred on python3.6 with numpy 1.12. 

Strangely, compiling and running identical code can sometimes fail and other times not, which is characteristic of weird memory issues with the F77 multisphere code.

This is a tricky issue to debug since it only occurs on Travis (so far), is not reproducible, and involves old F77 code. Hopefully it is fixed when we eventually upgrade to the F90 MSTM code.

**Comment by jeromefung** [comment]
I agree that this is going to be a pain to debug if it only happens
intermittently and in Travis. Out of curiosity, is it the same test or
tests that fail consistently, or does it seem random? About what fraction
of the time would you estimate this to be happening?

Jerome

**Comment by barkls** [comment]
It is usually the same tests, but not always the same number that fail.
Interestingly, low level tests have always passed, so the code is compiled,
it's just not passing values around properly. On builds that aren't
working, tests fail about 50-80% of the time, so it's not a rare one-off
problem that would go undetected.

**Comment by barkls** [comment]
Note that this is the only reason we had to require np>=1.12. If this is fixed, we can relax that dependency requirement.

**Comment by barkls** [comment]
Recently this has been happening on PR Travis builds but not master Travis builds.

**Comment by barkls** [comment]
@ellenklein encountered this (or a similar issue) on a mac running a conda-forge installation of holopy 3.2.1. She had scipy v1.1.0 and tried a few different numpy versions. She wasn't able to run calc_holo on any Spheres objects.

**Comment by briandleahy** [comment]
This has not appeared for >2  years, and with our current more-extensive test coverage, it seems to have been solved. It may have been a numpy issue.
