### ISSUE TITLE
Error in development guide and/or scatteringtheory.py

### ISSUE THREAD

**Issue by vnmanoharan** [manoharan-lab/holopy#195]
In the "Adding a new scattering theory" section of the Developer's Guide, it says

> You can get away with just defining one of _raw_scat_matrs or _raw_fields if you just want holograms, fields, or intensities.

This does not appear to be correct. If one defines `_raw_scat_matrs()` in a new theory, that does not allow calculation of the holograms, fields, or intensities, since the `_calc_field()` method of `ScatteringTheory` assumes that the subclass defines `_raw_fields()`. 

The problem seems to be that there is no default method `_raw_fields()` in the superclass `ScatteringTheory`. If such a method were implemented, the above statement in the developer guide would be true. Alternatively, the `get_field()` function of `ScatteringTheory._calc_field()` could be rewritten to first try calling `_raw_fields()` and, if that call fails, to then try calling `_raw_scat_matrs()` and calculating the fields directly from the scattering matrices.

**Comment by barkls** [comment]
This appears to be how dda actually calculates ``_raw_fields()`` already. It should be pretty simple to move the method up from DDA to the ScatteringTheory class. I will have a PR in soon.

**Comment by vnmanoharan** [comment]
OK - I've made a [3.1 branch](https://github.com/manoharan-lab/holopy/tree/v3.1). Let's put any bug fixes in there.  The bump up to 3.1 (instead of 3.0.1) is because I want to include the T-matrix theory too.
