### ISSUE TITLE
Docs don't read version from __init__.py

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#208]
Currently, the docs version number is specified in ``conf.py``, independently of the main version number in ``__init__.py``. We should have ``conf.py`` read in the version number from ``__init__.py`` but it's not completely trivial to do so since docs are not a submodule of HoloPy.

**Comment by vnmanoharan** [comment]
It looks like this can be done without changing the module structure:
https://stackoverflow.com/questions/26141851/let-sphinx-use-version-from-setup-py

Or we could just remember to update both.  

Is there any way to fix the badge in readme.rst that is reporting "docs: unknown version"?
