### ISSUE TITLE
Could not import Mie scattering theory / multisphere scattering theory - Fortran?

### ISSUE THREAD

**Issue by fpdx** [manoharan-lab/holopy#214]
Hi. After an apparently successful installation (I cloned and `sudo python3 setup.py install --record files.txt`), when I import holopy I get a warning and an error related to Mie, multisphere theory, and possibly Fortran compilation:

```
In [1]: import holopy as hp
/home/francesco/scripts/holopy/holopy/scattering/theory/mie.py:41: NoScattering: 
Could not import Mie scattering theory. You will not be able to do scattering 
calculations but the rest of HoloPy should remain usable. 
This is probably due to a problem with compiling Fortran code.
  warnings.warn(NoScattering('Mie'))

/home/francesco/scripts/holopy/holopy/scattering/theory/multisphere.py:49: NoScattering: 
Could not import multisphere scattering theory. You will not be able to do scattering
 calculations but the rest of HoloPy should remain usable. 
This is probably due to a problem with compiling Fortran code.
  warnings.warn(NoScattering('multisphere'))

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: 
Conversion of the second argument of issubdtype from `float` to `np.floating` 
is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
```
The test works well:
```
In [2]: from holopy import test_disp
   ...: test_disp()
```
But when I try to generate the example hologram, it fails:
```
In [3]: import holopy as hp
   ...: from holopy.scattering import calc_holo, Sphere
   ...: 
   ...: sphere = Sphere(n = 1.59, r = .5, center = (4, 4, 5))
   ...: medium_index = 1.33
   ...: illum_wavelen = 0.660
   ...: illum_polarization = (1,0)
   ...: detector = hp.detector_grid(shape = 100, spacing = .1)

In [4]: holo = calc_holo(detector, sphere, medium_index, illum_wavelen, illum_polari
   ...: zation)
```
with error:

`NameError: name 'miescatlib' is not defined`

I run debian stable (stretch), and these are the fortran packages installed:
```
gfortran/stable,now 4:6.3.0-4 amd64 [installed]
gfortran-6/stable,now 6.3.0-18 amd64 [installed,automatic]
libgfortran-6-dev/stable,now 6.3.0-18 amd64 [installed,automatic]
libgfortran3/stable,now 6.3.0-18 amd64 [installed,automatic]

```
Do you have any idea how I can solve this? (I need Mie theory)
Thanks

**Comment by barkls** [comment]
Hi fpdx, 

This looks like a fairly typical Fortran compiling issue. I'd like to point out that if you are just trying to use HoloPy, you should be able to install a ready-to-use package with conda. 

If you would like to be able to make any modifications to HoloPy, then you do need to install it on your system and compile the Fortran portions. As a first step, check if the compiled fortran files exist on your system, probably at: "/home/francesco/scripts/holopy/holopy/scattering/theory/mie_f/*.so".

If not, you can probably try to compile the fortran code manually with gfortran.

@vnmanoharan any advice on this?

**Comment by vnmanoharan** [comment]
@fpdx, if you can send us the output of running the setup.py script, we might be able to see where the Fortran compilation is going wrong.

**Comment by vnmanoharan** [comment]
Whoops, didn't mean to close.
