### ISSUE TITLE
Coordinate image saving and displaying

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#219]
Image brightness and contrast is auto-scaled when displaying images. This makes it difficult to compare two holograms, since their mapping will be different. We should have an option to pass in a scaling range, as when saving images.

**Comment by rgov** [comment]
This is said to be fixed in #253. Can it be closed?

**Comment by barkls** [comment]
Our workflow is to close issues only when they have been merged into the master branch, since the development branch is experimental and could be reverted.

**Comment by rgov** [comment]
Makes sense. How about a label you can affix to issues that have pending fixes? It would be a little easier for new contributors to tell what are open tasks.
