### ISSUE TITLE
"What's new" docs section

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#233]
It is standard for packages to have a "what's new" section in their documentation where they keep a record of updates with each release. We don't currently have this, but we list general features of each release on github.

**Comment by briandleahy** [comment]
Sending out a google doc now to the 2 of you; please add what is new to that google doc so we can divide up who writes which doc sections.

@barkls -- do you know which commit corresponds to the 3.2 release?

**Comment by barkls** [comment]
[The releases page](https://github.com/manoharan-lab/holopy/releases) (accessed from manoharan-lab/holopy homepage) has a link to the commit associated with each release. In this case it is https://github.com/manoharan-lab/holopy/commit/50cb2e5a2bc6103d655eda1ba4485e228db2ba3c.

**Comment by ralex0** [comment]
I think the Google doc is all set now.

**Comment by briandleahy** [comment]
Fixed by #314
