### ISSUE TITLE
hp.save_image auto scaling for two-color images

### ISSUE THREAD

**Issue by ykiriscioglu** [manoharan-lab/holopy#242]
`hp.save_image( "hologram", holo, scaling="auto")`
or 
`hp.save_image("hologram", holo)`
doesn't scale the images to the minimum and maximum intensity, when used for red-green holograms. When fed in the minimum and maximum values as a range for scaling, the code works, but otherwise the image gets saved differently.

**Comment by barkls** [comment]
I expect this is happening because the auto scaling is being calculated after adding a dummy blue channel.
