### ISSUE TITLE
Bug in SBESJY.F

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#249]
The algorithm used to calculate spherical Bessel functions in SBESJY.F sometimes fails near zeros of j_0(x). See example:

```
eps = 1e-12
d = hp.core.detector_grid(shape=10, spacing=1)
d = hp.core.update_metadata(d,illum_wavelen=1, medium_index=1, illum_polarization=(1,0))

s_exact = hp.scattering.Sphere(r=1,n=1.1,center=(5,5,5))
s_close = hp.scattering.Sphere(r=1,n=1.1,center=(5,5,5-eps))

h_exact = hp.scattering.calc_field(d,s_exact)
h_close = hp.scattering.calc_field(d,s_close)

hp.show(h_exact)
hp.show(h_close)
```
The best solution is probably to use scipy's new functions 'spherical_yn` and `spherical_jn`, which do not have this issue and function for large x (unlike the old scipy function `sph_jnyn`). However, there are a couple barriers to their implementation.
1) They are much slower than SBESJY, mostly because they don't return all orders of j_n and y_n so the function needs to be explicitly called for each n. Since the functions are calculated by a recurrence relation, this results in many repeated calculations behind the scenes, especially when many values of n are required. 
2) SBESJY is called from within fortran code, so there would need to be some reorganization to either calculate spherical Bessel functions from outside with python and pass them in, or call the scipy functions from within fortran.
3) @briandleahy pointed out to me that since this only occurs within ~10^-14 of some zeros, there is nearly zero probability of this bug ever being relevant by chance alone. It is only relevant when using simple test cases like the one shown above. 

Another possible solution is to modify the code in SBESJY to fix the bug. Basically, the un-normalized j_n(x) are calculated by downward recurrence. Then j_0(x) is calculated explicitly, and compared to the value from recurrence. All j_n(x) are scaled accordingly. This fails sometimes when j_0(x) is very close to zero. In those cases, it makes sense to calculate j_1(x) explicitly and rescale all j_n(x) by that instead.

**Comment by jeromefung** [comment]
I'm going to have to look more carefully at this -- but the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.spherical_jn.html) for `scipy.special.spherical_jn` suggests that it uses upwards recurrence. IIRC, part of the reason we used SBESJY is that upward recurrence for j_n is known to be unstable.

I'm not categorically opposed to switching to `scipy.special.spherical_jn` but would caution that some careful investigation of what it does exactly would be needed. I would be more inclined to modify SBESJY to catch cases when j_0 is small.
