### ISSUE TITLE
scipy optimize strategy returns incorrect uncertainties

### ISSUE THREAD

**Issue by eXpensia** [manoharan-lab/holopy#251]
I see that scipy.optimize is now used in the 3.3 version. I tested it and the uncertainties given are a bit strange (changing units doesn't change the values). I was wondering if using lmfit instead would be better, it extends many optimization options of scipy.optimize and also add directly a good uncertainties computation.

**Comment by barkls** [comment]
Hi eXpensia, thanks for the question. Here are a few comments:

1) HoloPy 3.3 is still an experimental version and is not fully tested or documented. That being said, everything _should_ work, so we appreciate your help in finding anything that doesn't.

2) The scipy.optimize fitting is a recent addition by @briandleahy. It's possible the uncertainties are not normalized to parameter values. It would be helpful to see the specific tests you did and the results you obtained to help us figure out if something is amiss.

3) The conventional lmfit code is definitely still supported in HoloPy, and can be accessed in the 3.3 API by defining a hp.inference.NmpfitStrategy object.

Let me know if this clears things up!
Solomon

**Comment by eXpensia** [comment]
Thanks for the answers, perfectly clear, I'll try to  format the test i made in the week to show you. I will also try to find what's going on.

**Comment by eXpensia** [comment]
Here it is, I used the example picture.

[uncertainties test.zip](https://github.com/manoharan-lab/holopy/files/2671645/uncertainties.test.zip)

**Comment by briandleahy** [comment]
This should be addressed on my fork. The scipy fitting strategy's uncertainties should now be correct; however, there is still a difference between the scipy and nmp strategies' uncertainties.

@barkls  and @ralex0 -- I'll touch base with you two on Thurs and we'll figure out what should be done, then I'll go ahead and make a PR.

**Comment by briandleahy** [comment]
Fixed by #311
