### ISSUE TITLE
Averaging images

### ISSUE THREAD

**Issue by ykiriscioglu** [manoharan-lab/holopy#252]
Using the function

` load_average(filepath, refimg=None, spacing=None, medium_index=None, illum_wavelen=None, illum_polarization=None, normals=None, noise_sd=None, channel=None, image_glob='*.tif')`

not only takes a lot of time to average over images, but it also freezes my screen and prevents me from doing anything on the computer. Given that I'm averaging over around 300 images, I understand that it takes a lot of time, but perhaps the freezing could be fixed.

**Comment by barkls** [comment]
I was worried the load_average function might not be closing files and keeping them in memory, but that seems not to be the case. The long evaluation time is probably just do the reading large numbers of large files from a networked drive. You could try copying the background files to a local drive beforehand. 

I also recommend calculating your averaged background image only once, and then saving it to a file for future use with hp.save (not hp.save_image).
