### ISSUE TITLE
HoloPy dependencies

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#255]
HoloPy has a lot of dependencies, with some new ones introduced in 3.3. Many of these (cma, emcee, h5, etc.) are only used in some parts of HoloPy and should be made optional, with intelligent error handling and test skipping to compensate when they are not present.

**Comment by rgov** [comment]
According to #259 this is fixed and should be closed, right?

**Comment by barkls** [comment]
Maybe. We might still try to remove more dependencies.
