### ISSUE TITLE
Error when runing Bayesian inference of Parameter Values example

### ISSUE THREAD

**Issue by kersthie** [manoharan-lab/holopy#264]
Hello, 
I am trying to run the example given in Bayesian inference of Parameter Values.
At first I got an AttributeError message that there is no attribute noise_sd in the image after bg_correct. According to the documentation the function should provide this attribute, but somehow it didn't.  I fixed the problem by adding a function that takes the standard deviation of the image via `np.std(data_holo)` and used that as noise_sd.

Nevertheless I am still getting an error when I run `result.best_fit()`

> AttributeError: 'TemperedSamplingResult' object has no attribute 'best_fit'

I tried backtracking where the error comes from but am not sure how to solve this. All the other attributes given in the example (such as `result.MAP` or`result.mean`) work fine.

**Comment by vnmanoharan** [comment]
Which version of HoloPy are you running?  The API for the inference calculations has changed a few times.

**Comment by kersthie** [comment]
It says version 3.0post1.
I installed it in the anaconda environment and tried updating it, but it says it's all up to date!?

**Comment by barkls** [comment]
try running `conda install -c conda-forge holopy==3.2.1` to upgrade to the most recent version.

**Comment by kersthie** [comment]
Thank you for your quick answeres it's working now. Im quite new to this so I'm not quite sure how things work.

**Comment by vnmanoharan** [comment]
Glad it's working.  Feel free to post other issues.
