### ISSUE TITLE
HoloPy paper uses FitResult.best_fit() as a method

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#266]
Right now it's a property in the 3.3 branch so the code examples in the HoloPy paper would fail.

I think the best solution is to rename the property and have the method point there.

This also solves the issue @briandleahy has raised that the name best_fit is ambiguous since it could refer to the best fit parameters or the forward model evaluated with best fit parameters.

**Comment by vnmanoharan** [comment]
It's also not clear what's meant by either "best" or "fit" (see #265). "best" could refer to the posterior mean, max, median, or any other point estimator. Let's fix #265 and get our object hierarchy straight first, and then perhaps the solution to this issue will present itself.

**Comment by barkls** [comment]
Fixed by #306. It introduces a `FitResult.hologram` property. Calling the `FitResult.best_fit()` method redirects there for now, with a message that this interface is deprecated.
