### ISSUE TITLE
Insufficient testing

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#280]
We identified a few of the worst files and assigned them to various developers to fix:

Goal is to write tests if it's straightforward, or flag for a refactor with tdd if it's a mess, so as to avoid spending time/effort writing tests for code that really needs to be rewritten

@barkls 
hp.scattering.scatterer.scatterer.py (and scatterers.py, sphere.py, spheres.py...)
hp.core.utils.py
hp.inference.prior.py, hp.inference.model.py

@briandleahy 
hp.core.metadata.py
hp.core.io.io.py (with @ralex0)
hp.scattering.theory.scatteringtheory.py
hp.scattering.theory.mielens.py
hp.scattering.theory.mielenstheory.py

@ralex0 
hp.core.io.vis.py 
hp.core.io.io.py (with @briandleahy)
hp.scattering.calculations.py
hp.scattering.errors.py

**Comment by briandleahy** [comment]
Adding more theory tests in #282

**Comment by barkls** [comment]
added tests to prior.py in #287

**Comment by briandleahy** [comment]
Testing metadata in #286

**Comment by barkls** [comment]
io and vis still aren't sufficiently tested but they should really be refactored since the code is in pretty bad shape. We made good progress on everything else!
