### ISSUE TITLE
AlphaModel - syntax error in v3.3

### ISSUE THREAD

**Issue by NRanta** [manoharan-lab/holopy#284]
I have adjusted the order of my inputs to be in the correct order.  s is my scatterer and noise_sd is defined already:

```model = AlphaModel(s,alpha=par(.6,[.1,1]),noise_sd)```

I am getting ```SyntaxError: positional argument follows keyword argument```

If I remove the alpha parameter it breaks, so what should I do to correct this?  Thank you.

**Comment by barkls** [comment]
Python requires that you provide all positional arguments before keyword arguments. Try
`model = AlphaModel(s, par(.6, [.1, 1]), noise_sd)`
or
`model = AlphaModel(s, alpha=par(.6, [.1, 1]), noise_sd=noise_sd)`
