### ISSUE TITLE
strat.sample index out of bounds

### ISSUE THREAD

**Issue by NRanta** [manoharan-lab/holopy#285]
When I do an inference for a sphere using the strat.sample, the indexes appear to be swapped.  I have a print statement in the model that displayed the first line in the outcome error.  Index 34 is being checked in axis 1 which is only size 30 while axis 2 is the one that has the size for it.  I was told to update v3.3 to the current build and this did not fix this issue.  Any recommendations?

```
Input code:

noise_sd = data_holo.std()
model = AlphaModel(s,alpha=par(.6,[.1,1]),noise_sd)
strat = TemperedStrategy()
result = strat.sample(model, data_holo)

Outcome error:

(29, 34, slice(None, None, None), Ellipsis)
Traceback (most recent call last):
  File "Niko_Test_Created_Hologram.py", line 71, in <module>
    result = strat.sample(model, data_holo)
  File "/home/ranta/miniconda3/lib/python3.7/site-packages/HoloPy-unknown-py3.7-linux-x86_64.egg/holopy/inference/emcee.py", line 81, in sample
    return self.optimize(model, data, nsamples, walker_initial_pos)
  File "/home/ranta/miniconda3/lib/python3.7/site-packages/HoloPy-unknown-py3.7-linux-x86_64.egg/holopy/inference/emcee.py", line 103, in optimize
    result = stage.optimize(model, data, nsamples=self.stage_len, walker_initial_pos=guess)
  File "/home/ranta/miniconda3/lib/python3.7/site-packages/HoloPy-unknown-py3.7-linux-x86_64.egg/holopy/inference/emcee.py", line 75, in optimize
    return SamplingResult(data, model, self, d_time, kwargs)
  File "/home/ranta/miniconda3/lib/python3.7/site-packages/HoloPy-unknown-py3.7-linux-x86_64.egg/holopy/inference/result.py", line 225, in __init__
    self.intervals = self._calc_intervals()
  File "/home/ranta/miniconda3/lib/python3.7/site-packages/HoloPy-unknown-py3.7-linux-x86_64.egg/holopy/inference/result.py", line 230, in _calc_intervals
    self.lnprobs.argmax(), self.lnprobs.shape)]
  File "/home/ranta/miniconda3/lib/python3.7/site-packages/xarray-0.11.3-py3.7.egg/xarray/core/dataarray.py", line 476, in __getitem__
    return self.isel(indexers=self._item_key_to_dict(key))
  File "/home/ranta/miniconda3/lib/python3.7/site-packages/xarray-0.11.3-py3.7.egg/xarray/core/dataarray.py", line 821, in isel
    ds = self._to_temp_dataset().isel(drop=drop, indexers=indexers)
  File "/home/ranta/miniconda3/lib/python3.7/site-packages/xarray-0.11.3-py3.7.egg/xarray/core/dataset.py", line 1528, in isel
    new_var = var.isel(indexers=var_indexers)
  File "/home/ranta/miniconda3/lib/python3.7/site-packages/xarray-0.11.3-py3.7.egg/xarray/core/variable.py", line 911, in isel
    return self[tuple(key)]
  File "/home/ranta/miniconda3/lib/python3.7/site-packages/xarray-0.11.3-py3.7.egg/xarray/core/variable.py", line 621, in __getitem__
    data = as_indexable(self._data)[indexer]
  File "/home/ranta/miniconda3/lib/python3.7/site-packages/xarray-0.11.3-py3.7.egg/xarray/core/indexing.py", line 1182, in __getitem__
    return array[key]
IndexError: index 34 is out of bounds for axis 1 with size 30```

**Comment by NRanta** [comment]
I found in the emcee.py that sample is depreciated as of v3.3 and changed it to strat.optimize.  This still did not resolve the issue.

I included a print statement for the indexers in xarray/core/dataarray.py - isel:
```{'walker': 22, 'chain: 85, ;parameter': slice(None, None, None)}```

where as the array shape from xarray/core/indexing.py - __getitem__ :
``` (100,30,2) ```

Any thoughts on this or is this normal?

**Comment by barkls** [comment]
Can you post a bit more detail about how to reproduce this unexpected behaviour? The code as you have written won't run because  you have a keyword argument before a positional argument in your instantiation of `AlphaModel`. 

If you have a complete minimal example (i.e. not on real data) that produces the bug that would be very helpful. 

It also looks like your HoloPy installation is within a conda directory, but the 3.3 development branch isn't available on conda. Can you run `from holopy.core.math import to_spherical` and let me know what happens?

**Comment by NRanta** [comment]
The location of the installation inside of conda is because of how the system was set up.  I was initially using holopy through conda and that became where python puts its installations.

When I run that I get 

```ImportError: Cannot import name 'to_spherical' from 'holopy.core.math' (/home/ranta/miniconda3/lib/python3.7/site-packages/HoloPy-unknown-py3.7-linux-x86_64,egg/holopy/core/math.py```

As for the AlphaModel, I am not sure what I was referencing with that.  The code I run does not include the alpha= in the second parameter.  It should read ``` AlphaMode(s,par(.6,[.1,1],noise_sd)```.

I doubt there following code will break, just guessing from math.py not having to_spherical that the holopy I am using is not complete.  But here is what I was running.

```
import holopy as hp
import numpy as np
import warnings
from holopy.core.io import get_example_data_path, load_average
from holopy.core.process import bg_correct, subimage, normalize
from holopy.scattering import Sphere, calc_holo, Cylinder, Capsule
from holopy.inference import prior, AlphaModel, TemperedStrategy
from holopy.fitting import fit, Model
from holopy.fitting import Parameter as par
warnings.simplefilter("ignore")


#Input hologram
#hologram = '00022'
fileName = '/home/ranta/holopy/Results/Test_Holo/test_holo4.tiff'

#Loading image
imagepath = get_example_data_path(fileName)
raw_holo = hp.load_image(imagepath, spacing = 0.1, medium_index = 1.33, illum_wavelen = 0.66,
                         illum_polarization = (1,0))

data_holo = normalize(raw_holo)


#Parameters for <capsule> are length, width, center, rotation
n = par(guess = 1.65, limit = [1.5,1.7])
rad = 9
x_loc = 30
y_loc = 30
z_loc = 40
center_loc = (x_loc, y_loc, z_loc)

# Defining a <sphere>
s = Sphere(n = n, r = rad, center = center_loc)


noise_sd = data_holo.std()
model = AlphaModel(s,par(.6,[.1,1]),noise_sd)
strat = TemperedStrategy()
result = strat.sample(model, data_holo)

hp.save('Test_Hologram_Scatterer.txt', result.MAP)```

**Comment by NRanta** [comment]
For forgot to mention, the test_holo4.tiff was a hologram created using holopy with n=1.59, r=9, center = (30,30,40) on a 600x600 canvas.  Was trying to just do basic work with getting the bayesian to work.

**Comment by barkls** [comment]
The fact that you can't import `holopy.core.math.to_spherical` proves that you are on the most recent version of HoloPy, which is strange because I can run your code without any errors. Here are a few steps to try to help me figure out what's going on.

1) Can you check if the following code works? It's a simplifed version of the code you sent, and it works without a problem on my machine.

```python
import holopy as hp
from holopy.core.process import normalize
from holopy.scattering import Sphere, calc_holo
from holopy.inference import prior, AlphaModel, TemperedStrategy
from holopy.fitting import Parameter as par

imagepath = 'test_holo5.tiff'
x =30; y=30; z=40; r=9

# Create hologram
s = Sphere(n=1.59, r=r, center=(x, y, z))
d = hp.core.detector_grid(shape=600, spacing=0.1)
h = calc_holo(d, s, 1.33, 0.66, (1,0))
hp.save_image(imagepath, h)

# Load image
raw_holo = hp.load(imagepath)
data_holo = normalize(raw_holo)

# Define model
n = par(guess = 1.65, limit = [1.5,1.7])
s = Sphere(n=n, r=r, center=(x,y,z))
model = AlphaModel(s, alpha=par(.6,[.1,1]), noise_sd=data_holo.std())

# Run fit
strat = TemperedStrategy(nwalkers=4, stages=2)
result = strat.sample(model, data_holo)
```
2) Can you check your numpy and xarray versions?

```python
import numpy as np
import xarray as xr
print(np.__version__)
print(xr.__version__)
```
3) I think you're right about the shape being tranposed somehow but I don't know exactly where you put the print statements. Can you edit the first few lines of `SamplingResult._calc_interval` in holopy/holopy/inference/result.py (lines 227-228 if you haven't made any other edits) as follows:

```python
    def _calc_intervals(self):
        print('sample shape', self.samples.shape)
        print('lnprob shape', self.lnprobs.shape)
        P_LOW = 100 * 0.158655253931457 # (1-scipy.special.erf(1/np.sqrt(2)))/2
```

**Comment by NRanta** [comment]
1) Error in the same manner is previous

2) numpy was 1.16.4, upgraded to 1.17.0 (error present after upgrade) /// xarray was 0.12.3 (previously upgraded this as I thought this might have been the culprit)

3) Results of the print statements:
sample shape (4, 30, 2)
lnprob shape (30,4)

**Comment by barkls** [comment]
Ok I think I've figured it out. Can you check your emcee version?
```python
import emcee as emcee
emcee.__version__
```
It should be 2.2.1. There is a pre-release version 3 of emcee, but we haven't transitioned HoloPy to use it yet. I suspect you might have that version installed.

**Comment by NRanta** [comment]
That seems to have fixed it, indeed I was somehow using the pre-release version 3 of emcee.  I uninstalled v3 and got v2.2, the shapes then matched up corrected (the script you included ran to completion without an error).  Thank you very much for your help with this!
