### ISSUE TITLE
Travis pins version numbers

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#299]
As of 3.3 release, travis.yml pins a few things that should be updated in future.

I've edited this comment to keep the below list up to date:
python 3.6 (for compatibility with h5netcdf 0.7.4) - [code runs with DeprecationWarnings]
h5py 2.9 (for compatibility with h5netcdf 0.7.4) - [code runs with DeprecationWarnings]
yaml < 0.2 or pyyaml < 5.2 - [code doesn't run]
scipy < 1.4 [code doesn't run]

**Comment by barkls** [comment]
Pinning "yaml<0.2" since they have removed support for `OrderedDict` (as that's just a dictionary now). We use `OrderedDict` within HoloPy, but it's also used extensively throughout xarray so we are running into problems reading/writing yaml. [@ralex0 you'll love this one!]

**Comment by briandleahy** [comment]
I updated a problem with scipy #328 and with xarray and cma in #332 . We still have h5 and yaml / pyyaml pinned.

**Comment by barkls** [comment]
Everything's working on my system with the following most recent versions (only showing relevant packages), so we can probably remove pins and close this issue. Then if a new incompatibility crops up later, we'll catch it because Travis will start failing.


#### Name                    Version                   Build  Channel
h5netcdf                  0.8.1                      py_0    conda-forge
h5py                      2.10.0           py38h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
numpy                     1.19.2           py38hadc3359_0
python                    3.8.5                h5fd99cc_1
pyyaml                    5.3.1            py38he774522_1
scipy                     1.5.2            py38h14eb087_0
xarray                    0.16.1                     py_0
yaml                      0.2.5                he774522_0

**Comment by briandleahy** [comment]
Sounds good to me. I think this merits its own PR (into the dev branch), since otherwise it will get confusing figuring out the sources of errors. 

If you do it, I will merge it in as soon as it passes on Travis.
