### ISSUE TITLE
adda for n_cpu > 1 not storing geometry

### ISSUE THREAD

**Issue by NRanta** [manoharan-lab/holopy#300]
*For v3.3

I am wanting to run mpi with the hope of decreasing the calculation time for the capsule shape.  When I have n_cpu > 1 the check_call fails and no run000* directories are created.  When I then take the check_call cmd that failed and run it by itself the error is not present and the run000* are created.

I attempted to upload screenshots of the error, but github is not letting me do so.  Will try again later to upload them if needed.

**Comment by vnmanoharan** [comment]
I don't think MPI on ADDA has been tested extensively.  If you can send us some code to reproduce the error, that would be helpful.

**Comment by NRanta** [comment]
Here is the code that I am running.  Mine uses a .tiff file, but I changed the code to allow for github not being able to send that file format.

![00006_holo](https://user-images.githubusercontent.com/46546279/67340099-87857480-f4e1-11e9-83bd-59cafe3cf1d8.jpg)




import os
import timeit
import holopy as hp
import numpy as np
import warnings
import h5py
import matplotlib.pyplot as plt
from holopy.core.io import get_example_data_path, load_average
from holopy.core.process import bg_correct, subimage, normalize
from holopy.scattering import Sphere, calc_holo, Cylinder, Capsule
from holopy.inference import prior, AlphaModel, TemperedStrategy
from holopy.fitting import fit, Model
from holopy.fitting import Parameter as par
from shutil import copy2
warnings.simplefilter("ignore")

#Start timer
start_time = timeit.default_timer()

#Naming of file
date = 22
file = str(date)
month = 'October'
shapes = 'Capsule'
run = "run_1"
method = "bayesian"
#parameters of the optimize function (only change if certain as this messes with time for completion and accuracy)
nwalkers = 30
nsamples = 80

#Creates a folder for the date code is started should one not exist.
if not os.path.exists('/Users/nadeau/Documents/Holopy_Results_Cluster/'+month+'_'+file):
   	os.mkdir('/Users/nadeau/Documents/Holopy_Results_Cluster/'+month+'_'+file)
#Copies this script file into date folder for the purpose of tracking code changes
copy2('Niko_Capsule.py',''+month+'_'+file+'/Niko_Capsule_'+run+'.py')

#########################################################################################
####    Call and load input hologram
#########################################################################################
#Input hologram
hologram = '00006'
fileName = '/Users/nadeau/Documents/Holopy_Results_Cluster/'+hologram+'_holo.jpg'

#Loading image
imagepath = get_example_data_path(fileName)
raw_holo = hp.load_image(imagepath, spacing = 0.178, medium_index = 1.33, illum_wavelen = 0.405,
                         illum_polarization = (1,0))

#Process the image, isolate area of interest, then normalize
data_holo2 = subimage(raw_holo, [590,950], 200)
data_holo = normalize(data_holo2)


#########################################################################################
####    Defining parameters and Utilize ADDA to generate a scattered field for <capsule>
#########################################################################################

#Parameters for <capsule> are length, width, center, rotation (radians)
bact_length = prior.Uniform(6,8.5) #Length of bacteria (4um to 10um)
bact_width = prior.Uniform(.2,.5) #Diameter of bacteria (.25um to 1.0um)
x_loc = 105 #position of particle in X
y_loc = 169 #position of particle in y
z_loc = prior.Uniform(79,81) #unknown position of particle in z
center_loc = (x_loc, y_loc, z_loc)
rotation1 = prior.Uniform(.85*np.pi/2,1.15*np.pi/2) #Rotation around y-axis (occurs first)
rotation2 = prior.Uniform(-.1*np.pi/2,.1*np.pi/2) #Rotation around z-axis (occurs second)
rotation0 = 0 #Leave as 0 unless object is not symmetric through its major axis

# Defining a <capsule>
c = Capsule(n = 1.53, h = bact_length, d = bact_width, center = center_loc,
             rotation = (rotation0, rotation1, rotation2))

#########################################################################################
####    Bayesian inference
#########################################################################################
# Set up the noise model
model = AlphaModel(c,alpha=par(.6,[.1,1]),noise_sd=data_holo.std())
strat = TemperedStrategy(nwalkers=nwalkers, stages=2)
#print("Time to finish: ", timeit.default_timer() - start_time)
result = strat.optimize(model, data_holo, nsamples=nsamples)

#########################################################################################
####    Save results
#########################################################################################
hp.save('/Users/nadeau/Documents/Holopy_Results_Cluster/'+month+'_'+file+'/'+hologram+'_'+shapes+'_'+method+'_590_950_scatterer_'+month+'_'+file+'_'+run+'_'+str(nwalkers)+'_'+str(nsamples)+'.txt', result.scatterer)
#print duration of code
print("Time to finish: ", timeit.default_timer() - start_time)

**Comment by NRanta** [comment]
I was worried that it would not work, but if I run the code fails the check_call it does not error out.  So I am not sure that it is something ADDA itself is doing wrong.

Error with command listed: ![mpi_error](https://user-images.githubusercontent.com/46546279/67421902-46936b80-f586-11e9-9713-325eb3eb7d1f.jpg)
Same command running to completion in new terminal tab: ![mpi_works](https://user-images.githubusercontent.com/46546279/67421901-46936b80-f586-11e9-8db6-99a756989ec3.jpg)

**Comment by vnmanoharan** [comment]
It looks like `mpiexec` is terminating with [error code 1](https://www.open-mpi.org/doc/v3.0/man1/mpiexec.1.php#sect25).  This means that `adda` either didn't execute or terminated before `mpiexec` expected it to.   Can you check to make sure `adda` is in your path?
