### ISSUE TITLE
extra docs file pushed

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#307]
There's a .h5 file in the docs folder that appears to have come from running doctests. It should be deleted, and a corresponding filter added to .gitignore.

**Comment by vnmanoharan** [comment]
If it's a big file, can you rebase rather than delete?  That will help keep the repo size down.

**Comment by barkls** [comment]
Please ignore the auto-generatedcomment referencing this issue above.

The file was large, so I made a [new rebase branch](https://github.com/manoharan-lab/holopy/tree/3.3-rebase) in this repository. We can't merge with a PR, but it would be nice if someone can at least visually look over the differences between the two branches using the "Compare" button. Ideally all differences are symmetric when switching head and base branches (except for the missing file).

Let me know if there's a better tool to make this comparison!

**Comment by barkls** [comment]
Ok I've tried this again - I pushed to the 3.3-rebase branch. If you pull that and do a local `git diff` vs. 3.3, there shouldn't be any changes except the large .h5 file in git history that exists on `3.3` but not `3.3-rebase`.

Can somebody confirm this?

**Comment by briandleahy** [comment]
Yes. If I do
```
git diff --name-only 1c14981 da608ed
```
I only see 
```
docs/results_file.h5
```
which is there on 3.3 but not on 3.3-rebase.
