### ISSUE TITLE
Z vs R variations in a sphere

### ISSUE THREAD

**Issue by NRanta** [manoharan-lab/holopy#318]
I am running into an issue where the spherical objects that I am attempting to determine information about using holopy is not converging on a consistent value.  For my code I have only Z and R as free parameters and when I perform 20 calculations I get each parameter spanning 95%+ of the range of possible inputs.  My z-depth is around 140-150 and radius is around 1.

[removed simulation stuff as I incorrectly subtracted holograms in Fiji, the question still holds as results are not converging]

What should I do in this situation?  I attempted to up the contrast of the input hologram and extend the alpha lower, these did not change anything (not that I fully expected them to).  I have also let walkers = 200 and stages = 1000, only to still have no convergence.

Attached is my code, apologies for how ugly it looks, and the three simulation differences.
[Spheres.docx](https://github.com/manoharan-lab/holopy/files/4036997/Spheres.docx)

**Comment by ralex0** [comment]
Hi @NRanta are you sure your particles are that far away in z distance? I'd think a 1.0 micrometer, n=1.38 particle in water (n=1.33) would be pretty hard to see from 150 microns away. This code below creates a [simulated hologram](https://imgur.com/a/kjwnAQQ) with these parameters. There's no structure in the hologram, so it would be impossible for the sampling to converge to the correct result.

```python
import holopy as hp
from holopy.scattering import calc_holo, Sphere

sphere = Sphere(n = 1.38, r = 1.0, center = (5, 5, 150))
medium_index = 1.33
illum_wavelen = 0.660
illum_polarization = (1,0)
detector = hp.detector_grid(shape = 100, spacing = .1)

holo = calc_holo(detector, sphere, medium_index, illum_wavelen, illum_polarization)
hp.show(holo)
``` 

Also, are you using the current version of holopy? This is how I would do the calculation with the current API.

```python
import datetime
import os
import timeit

import holopy as hp
from holopy.core.process import subimage, normalize
from holopy.scattering import Sphere
from holopy.inference import prior, AlphaModel, TemperedStrategy

TODAY = datetime.date.today().isoformat()
PREFIX = '/Users/nadeau/Documents/Holopy_Results_Cluster/'
NWALKERS = 100
NSAMPLES = 500
NUMBER_OF_RUNS = 1


def load_input_hologram(filename, particle_location):
    imagepath = os.path.join(PREFIX, f'{filename}.tif')
    holo = hp.load_image(imagepath, spacing=0.1285, medium_index=1.33,
                         illum_wavelen=0.405, illum_polarization=(1, 0))
    holo = subimage(holo, particle_location, 300)
    holo = normalize(holo)
    return holo


def guess_scatterer():
    n = 1.38
    radius = prior.Uniform(.8, 1.5)
    x_loc = 143
    y_loc = 145
    z_loc = prior.Uniform(148, 151)
    center_loc = (x_loc, y_loc, z_loc)
    return Sphere(n=n, r=radius, center=center_loc)


def alpha_guess():
    return prior.Uniform(.2, [.01, 1])


if __name__ == '__main__':
    input_filename = '00188_holo_Contrast2'
    particle_location = [906, 966]

    data_holo = load_input_hologram(input_filename, particle_location)

    guess_scatterer = guess_scatterer()
    alpha_guess = alpha_guess()

    print("Starting inference")
    for run in range(NUMBER_OF_RUNS):
        now = datetime.datetime.utcnow().isoformat()
        start_time = timeit.default_timer()

        model = AlphaModel(guess_scatterer, alpha=alpha_guess,
                           noise_sd=data_holo.std())
        strategy = TemperedStrategy(nwalkers=NWALKERS, stages=2)
        result = strat.optimize(model, data_holo, nsamples=NSAMPLES)
        output_filename = os.path.join(PREFIX, 'Holopy_Results_Cluster',
                                       'test_inference',
                                       f'result_run_{str(run)}_{now}')
        print('Time to finish run {run + 1}/{NUMBER_OF_RUNS}: ',
              timeit.default_timer() - start_time)

        hp.save(output_filename, result)
        print('Result saved to {output_filename}'')
```

**Comment by NRanta** [comment]
Looking through my code I used the wrong spacing, got it mixed up with a different hologram set.   
 I set the spacing to be 0.1285 instead of 0.178.  That said.  This is the [simulated hologram](https://imgur.com/HqmmKk4) that I got back with my dimensions.  You used shape = 100 and spacing = 0.1, for my hologram I subimage to a shape = 300 and the spacing is a 0.178.  This results in a drastically different outcome and one that does have structure.

```
import holopy as hp
from holopy.scattering import calc_holo, Sphere

sphere = Sphere(n = 1.38, r = 1.0, center = (26.7, 26.7, 150))
medium_index = 1.33
illum_wavelen = 0.405
illum_polarization = (1,0)
detector = hp.detector_grid(shape = 300, spacing = .178)

holo = calc_holo(detector, sphere, medium_index, illum_wavelen, illum_polarization)
hp.show(holo)
```

Here is the method I used to locate where the object was located:

```
import numpy as np
import holopy as hp
from holopy.core.io import get_example_data_path
from holopy.core.process import subimage

imagepath = get_example_data_path('00188_holo.jpg')
raw_holo = hp.load_image(imagepath, spacing = 0.178, medium_index = 1.33, illum_wavelen = 0.405)
data_holo = subimage(raw_holo, [906,966], 300)


zstack = np.linspace(0, 200, 201)
rec_vol = hp.propagate(data_holo, zstack)
hp.show(rec_vol)
```

Here is the hologram in question, it was changed to a jpg as tif is not an acceptable image format.  The object that I am isolating is at [906,966].
![00188_holo](https://user-images.githubusercontent.com/46546279/72472474-7757fb00-3799-11ea-81f8-5eb161a61a13.jpg)


I am going to re-run in with the proper spacing and see if it can come back with something semi-consistant.

**Comment by ralex0** [comment]
Were you able to get reasonable results yet? Sorry for the late response! I guess that you've found all this out by now, but I just want to write it down here for anyone reading this in the future. 

From that hologram, it doesn't look like your particles are 150 microns away. Those particles look pretty close to the focus, or rather close in `(focal distance)/(size parameter)`. Also, your suspension is pretty dense. Too dense to work with [single particle] Mie theory. All the particles in frame are convoluted with the fringes of their neighbors (i.e. the fringes are overlapping.) If you are fitting cropped sub-images of that hologram to Mie theory, you will probably have some trouble. 

I'm closing this because I think it is not related to a bug in holopy. Contact me at ralexander@g.harvard.edu to continue this thread. If we figure anything out, I promise to post it here later for posterity.
