### ISSUE TITLE
Make Scattering theories into simple functions

### ISSUE THREAD

**Issue by tdimiduk** [manoharan-lab/holopy#32]
The scattering theories are currently classes with magical functions that let you call calculation functions as if they were normal functions. 

We decided to make the scattering theories into objects because we thought it would be useful for having theory settings, but in practice this is almost never used. 

The code that allows the current api is kind of excessively magical (uses inspect and a decorator that inserts functions into an object's dictionary) and is a bit brittle to things like pickling (needed for multiprocessing support). So it is probably more hassle and maintenance burden than it is worth.

**Comment by vnmanoharan** [comment]
I think pickling is now implemented for the theory classes.  @tdimiduk, can you confirm and close this issue if it is?
