### ISSUE TITLE
Saving of reconstruction volume plots

### ISSUE THREAD

**Issue by MatthiasGi** [manoharan-lab/holopy#323]
To save a hologram plotted by the library one can simply write:
```python
hp.show(holo)
plt.savefig("holo.png")
```

For reconstruction volume this isn't as easy because the images are "hidden" behind keystrokes. I therefore extended `holopy.core.io.vis.py` to offer methods for this use case. A similar thing could be done to `holopy.core.io.io.py` for the `save_image`-method.

Is there any interest in my changes? I'm happy to make a pull request for them. Or are there already good methods to achieve what I want (that simply aren't documented).

**Comment by barkls** [comment]
It's true that there isn't a good way in HoloPy to save a reconstruction stack, and a pull request adding that functionality would be appreciated. Unfortunately the code in `holopy.core.io.vis.py` and `holopy.core.io.io.py` is some of the messiest in HoloPy and should be completely refactored at some point. However, There's no timeline for this, and anything you add would be incorporated into    any rewriting of these files.

**Comment by briandleahy** [comment]
Fixed by #324 and #325
