### ISSUE TITLE
image01 demo question

### ISSUE THREAD

**Issue by fsonnichsen** [manoharan-lab/holopy#326]
I have keyed in the image reconstruction code from page 13 of the documentation using the image01 demo. I get results but the output appears as successive diffraction patterns (holograms) along the z axis. I was expecting the output to be reconstructed "visual" slices through a solid object.
   Can someone tell me what original object was (a sphere perhaps?).  And am  misinterpreting this or is the output to be a set of "visual" image slices layered along the z axis?

Thanks
Fritz - Woods Hole Oceanographic Inst

**Comment by barkls** [comment]
Hi Fritz,

The `hp.propagate` function reconstructs the electromagnetic field at multiple planes defined by their distance from the detector. You can think of this as being similar to adjusting the defocus distance while the hologram was being recorded. There is a sphere that comes into focus near z=18 in the example problem. This sphere is approximately the same size as the wavelength of light, so it wouldn't be possible to resolve any finer details about its shape even if it were more interesting. Reconstruction cannot accurately provide the 3D shape of larger objects either, as it is not possible to predict the internal electromagnetic fields without knowledge of the object, unless it can be approximately modeled as the same as the medium. Reconstruction is most useful for particle localization. A hologram containing multiple particles at different (x, y, z) coordinates will show each one coming into focus at their own respective reconstruction heights.
