### ISSUE TITLE
`determine_default_theory_for` picks Multisphere for two spheres even when they are far apart, which causes problems

### ISSUE THREAD

**Issue by briandleahy** [manoharan-lab/holopy#338]
See this discussion, take from @jeromefung in #337 
> This stemmed from a recent email exchange I had with a HoloPy user who was obtaining some unphysical results when calculating holograms with the default scattering theory (Multisphere) for multiple spheres separated by many particle diameters. There's nothing in the documentation to suggest using Mie in such a case.

> The real issue the user was encountering was that Multisphere expands the scattered fields in vector spherical harmonics whose origin is at the center of mass of all the spheres. Apparently, the default limits on the expansions by scsfmo1b weren't enough for the user's situation (but in that situation, optical coupling was negligible).

One solution would be for `determine_default_theory_for` to check if the spheres are far enough apart where Mie Superposition would be a better approximation than Multisphere. 

However, this solution could be problematic during an inference calculation if the spheres sit near the cutoff distance for switching between Mie and Multisphere. I can imagine a situation where the best fit with Multisphere places the spheres far enough apart for Mie Superposition to be used, and the best fit with Mie Superposition places the spheres close enough together to use Mie Superposition, and the inference algorithm constantly switches back and forth between those two. If someone is unlucky this could cause convergence issues unless the theory is specified once per inference calculation and does not switch. 

As a temporary measure we can add a discussion in the user guide regarding this.

**Comment by barkls** [comment]
I think the inference case is easily solved by having the model call `determine_default_theory` upon instantiation. This should be the behaviour regardless of the main point here, because an inference calculation `FitResult` object is supposed to store all the information needed to redo the calculation, but right now it might not know what theory was used and defaults change.

**Comment by briandleahy** [comment]
Fixed by #393.
