### ISSUE TITLE
Lens calculations aren't documented

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#345]
The `MieLens` model and WIP general lens case #333 aren't referenced at all in the documentation. Especially with the lens paper out mentioning the code is available in holopy, it would be nice to have some instructions somewhere.

**Comment by briandleahy** [comment]
We should probably:
1. Add a brief description to the tutorial on the lens theories, as a short term solution. 
2. Add a ScatteringTheory user's guide, along the lines of #344 , as a longer term solution.
