### ISSUE TITLE
Move scattering.theory.mie_f.mie_specfuncs.log_der_1 to fortran

### ISSUE THREAD

**Issue by tdimiduk** [manoharan-lab/holopy#35]
scattering.theory.mie_f.mie_specfuncs.log_der_1 can take > 10 percent of runtime for a low fraction Mie calculation. It is a short function that should be pretty easy to move to fortran and see a noticeable speedup.

**Comment by vnmanoharan** [comment]
Is this fixed by #37 ?

**Comment by tdimiduk** [comment]
Yes it is.
