### ISSUE TITLE
[question] How to overcome the tolerance of system setup

### ISSUE THREAD

**Issue by funs** [manoharan-lab/holopy#396]
Hi All,

I built up a system with 
Z1 = 40 mm (distance from camera to object)
Z2 = 160 mm (distance from pinhole to object)

However , there exists a little mechanical tolerance.

How should I fine tune the parameters?

Thank you very much.

ps. sorry for my poor English.

**Comment by briandleahy** [comment]
Sorry for the delayed response @funs . Can you clarify your question a bit? Are you asking about a problem with holopy, or are you asking about how to better design your experimental setup? I don't think we can help you improve the design of your experiment, but if you have a bug or question about holopy we can try to help.

**Comment by funs** [comment]
@briandleahy 

Thank you for your reply.
I'm asking about how you guys make sure the parameters fits your system setup due to the tolerance of design.
For example, the design value of distance from pinhole to object is 160 mm, but the real value is (160 -0.01) mm. The tolerance is -0.01 mm.

**Comment by briandleahy** [comment]
Unfortunately the answer to your question is experiment specific, so I can't help you.

When I am analyzing data and I have some uncertainty in the set up, usually I start by asking myself what the goal of the analysis is. If the goal is something qualitative (does the experiment look like the data?) or if it's something quantitative (what precisely is the radius of this sphere?) I may approach the problem differently. Some things I might try are:

* Measuring the unknown parameter as carefully as possible. 
* Re-doing the analysis with multiple values of the parameter, to see how sensitive the analysis is to different values of the parameter.
* Letting the unknown parameter be a free parameter in a fit, fitting the parameter to find the best value, and including the effects of the fitted parameter in my reported uncertainties for the desired measurement (i.e. marginalization).

But the best thing to do will depend on what your goals are for the measurement. If you're doing reconstruction just to see what something looks like, then I would suggest doing multiple reconstructions with different values of the setup, to see if the feature you are searching for is robust to the finite tolerance of the experimental setup.

**Comment by funs** [comment]
Dear @briandleahy ,

Thank you very much ^__^
