### ISSUE TITLE
[question] How do I get the sphere depth out of a reconstruction?

### ISSUE THREAD

**Issue by gui-miotto** [manoharan-lab/holopy#402]
Hi there, is there a function in holopy that estimates the depth of spheres from a reconstruction volume? If not, do you know if this code is available somewhere?

Another question: I could use the inference method to get those depths, right? Does inference works well if the hologram has a large number of spheres (something like. 500)?

**Comment by barkls** [comment]
There isn't a simple function to do this - in general it depends on a lot of factors so isn't easy to automate the general case. If you know the approximate size of your spheres and reconstruction slice resolution you can ad-hoc something that works fairly well by looking for the centers of spheres switching from dark to light.

We often use reconstructions to find an initial guess for the inference method, which can then provide a better measurement for the depth of each sphere. Unfortunately inference can't handle 500 spheres right now - there are difficulties both for calculating a hologram with that many spheres, and also for optimizing in such a high parameter space. Personally I wouldn't go above 20 spheres or so.

**Comment by gui-miotto** [comment]
Thanks @barkls for the nice comprehensive answer!
