### ISSUE TITLE
Background Grayscale changes

### ISSUE THREAD

**Issue by nan20220609** [manoharan-lab/holopy#418]
Using calc_holo to calculate the particle hologram and hp.propagate to reconstructe in different z, it was found that the z-background grayscale changed significantly. 

holo = calc_holo(detector, sphere, medium_index, illum_wavelen, illum_polarization=(0, 1), theory='auto')
rec_vol = hp.propagate(holo, z)

As shown in the following figure：
[rec_vol_1000](https://github.com/manoharan-lab/holopy/assets/107190128/dec7c22c-9fb6-43cc-a18f-a67c7e43b753)
[rec_vol_1500](https://github.com/manoharan-lab/holopy/assets/107190128/d0bcf864-b2a7-417a-954c-6d2926032880)
Does anyone know why？

**Comment by vnmanoharan** [comment]
Propagation and reconstruction return an array of complex quantities, so the background will depend on which real quantity you are plotting: amplitude, phase, or intensity.  Plotting the phase, for example, will show variations in the background with z.  Variations in background can also arise from out-of-focus objects.
