### ISSUE TITLE
The center of the particle is brighter than the surroundings

### ISSUE THREAD

**Issue by nan20220609** [manoharan-lab/holopy#419]
When describing particles, especially irregular particles, the center of the particle is brighter than the surrounding after reconstruction.
Does anyone know why this is？

**Comment by vnmanoharan** [comment]
The reconstructed image will look different depending on whether you are looking at the real part, imaginary part, amplitude, or phase. If this is still an issue for you, feel free to re-open with some example code and results that illustrate the problem.
