### ISSUE TITLE
Coordinate system X and Y swapped?

### ISSUE THREAD

**Issue by cmdlinebeep** [manoharan-lab/holopy#444]
Hello, new the HoloPy library, and I did not see this mentioned anywhere in the docs.. but it seems to me that the `load_image()` function has coordinates swapped?  Or quite likely I'm understanding something wrong here.

I am loading some .tiff images that I *know* (by inspection and by reading their file properties in my OS), are 4024px **wide** and 3036px **tall**.

But when I run the following:

```
holo = hp.load_image(sorted(files)[i], spacing=1)
print(f"holo coordinates: {holo.coords}")
```

I get:

```
holo coordinates: Coordinates:
  * z        (z) int32 4B 0
  * x        (x) int32 12kB 0 1 2 3 4 5 6 ... 3029 3030 3031 3032 3033 3034 3035
  * y        (y) int32 16kB 0 1 2 3 4 5 6 ... 4017 4018 4019 4020 4021 4022 4023
```

Where the shorter axis is being referred to as X here.  I know in image processing it's conventional to index an array by [height, width], but when actually naming the axes I would expect that indexing along a row would be called X.

Have I got something set up wrong?

**Comment by vnmanoharan** [comment]
You're not doing anything wrong -- that's how the coordinate system is set up (see [here](https://holopy.readthedocs.io/en/master/users/concepts.html#coordinate-system) for a diagram).  There's a bit of historical baggage here.  Before we started using arrays with labeled dimensions, we were using NumPy arrays. We called the first dimension of these arrays "x" to maintain an [x,y] indexing convention.  When we moved to labeled dimensions we didn't want to change that convention.

**Comment by cmdlinebeep** [comment]
Ah, thank you for that clarification!  It seems I got stuck on this before getting that far into the guide.  :-)

One suggestion I'd add is that that link says the reason for those X/Y axes convention is:  "This corresponds to the way that images are treated by most computer software." which I'd argue is not true and might be better to reword that as explaining the historical code baggage instead, if I could make that suggestion.
