### ISSUE TITLE
Why can't I install HoloPy on Mac M2 ？

### ISSUE THREAD

**Issue by 73Emilie** [manoharan-lab/holopy#445]
I followed the installation notes, and the result is as follows:

```
(base) emiliefeng@EmiliedeMacBook-Air ~ % conda install -c conda-forge holopy  
Channels:  
 - conda-forge  
 - defaults  
Platform: osx-arm64  
Collecting package metadata (repodata.json): done  
Solving environment: failed  

PackagesNotFoundError: The following packages are not available from current channels:  

  - holopy  

Current channels:  

  - https://anaconda.anaconda.org/conda-forge  
  - defaults  

To search for alternate channels that may provide the conda package you're looking for, navigate to  

    https://anaconda.org  

and use the search bar at the top of the page.
```
Is there anyone who can help me?

**Comment by vnmanoharan** [comment]
The conda-forge channel seems to be specified incorrectly.  Try doing
```
conda config --remove channels 'https://anaconda.anaconda.org/conda-forge'
```
and then
```  
conda config --add channels conda-forge
```
Then try running the installation again..

**Comment by 73Emilie** [comment]
sorry, I'm still confused：
`(new_holopy_env) emiliefeng@EmiliedeMacBook-Air ~ %  conda config --show channels
channels:
  - conda-forge
  - defaults
(new_holopy_env) emiliefeng@EmiliedeMacBook-Air ~ % conda install holopy
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - holopy

Current channels:

  - https://conda.anaconda.org/conda-forge
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


(new_holopy_env) emiliefeng@EmiliedeMacBook-Air ~ % conda config --remove channels 'https://anaconda.anaconda.org/conda-forge'

CondaKeyError: 'channels': value 'https://anaconda.anaconda.org/conda-forge' not present in config

(new_holopy_env) emiliefeng@EmiliedeMacBook-Air ~ % conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top
(new_holopy_env) emiliefeng@EmiliedeMacBook-Air ~ % `

**Comment by 73Emilie** [comment]
sorry, I'm still confused：

`(new_holopy_env) emiliefeng@EmiliedeMacBook-Air ~ %  conda config --show channels
channels:
  - conda-forge
  - defaults
(new_holopy_env) emiliefeng@EmiliedeMacBook-Air ~ % conda install holopy
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - holopy

Current channels:

  - https://conda.anaconda.org/conda-forge
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


(new_holopy_env) emiliefeng@EmiliedeMacBook-Air ~ % conda config --remove channels 'https://anaconda.anaconda.org/conda-forge'

CondaKeyError: 'channels': value 'https://anaconda.anaconda.org/conda-forge' not present in config

(new_holopy_env) emiliefeng@EmiliedeMacBook-Air ~ % conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top
(new_holopy_env) emiliefeng@EmiliedeMacBook-Air ~ % `

**Comment by vnmanoharan** [comment]
At the moment, we don't have packages built for Apple Silicon chips (M1 and higher, osx-arm64) on conda-forge.  Sorry about that.  This is scheduled to be fixed in the next release.  

There are a couple of workarounds for now:
1. You can try to build from source.  To do this, clone the repository and then follow the instructions in the INSTALL.txt file.
2. You can setup an x64 environment on conda (here are [some instructions](https://stackoverflow.com/a/71554275)) and then do `conda install holopy` from this environment.  This will download and install the osx-64 package, which will be slower than a native ARM version but should work fine.

**Comment by 73Emilie** [comment]
Thanks, I've got it sorted.
