### ISSUE TITLE
Which scattering theory should I use for point source illumination of polysphere?

### ISSUE THREAD

**Issue by 73Emilie** [manoharan-lab/holopy#447]
I'm conducting experiments with polysphere and trying to compare my experimental images with theoretical predictions using Mie theory. After inputting experimental parameters, I found significant discrepancies between the theoretical and experimental results. After various comparisons, I suspect this might be due to my use of a point source illumination instead of a plane wave.

My question is: When using a point source illumination (spherical wave) rather than a plane wave, which scattering theory would be more appropriate for calculating the scattering patterns of polysphere?

**Comment by jeromefung** [comment]
Thank you for your message. Currently, holopy does not implement scattering of a beam from a point source. It can perform _reconstruction_ of holograms that were illuminated by a point source, but that's quite different from what you're asking about.

All the scattering calculations in holopy and the codes that perform them (including Lorenz-Mie theory, multisphere superposition, and the discrete dipole approximation) assume an incident plane wave. Except in the very far field, the wave from a point source differs significantly from a plane wave. Implementing non-plane-wave illumination would be a significant undertaking.

If you were interested in pursuing this further, I'd suggest looking at the papers of Gerard Gouesbet and co-workers on generalized Lorentz-Mie theory.

**Comment by 73Emilie** [comment]
Thank you for your previous response! After rechecking my experimental setup, I confirmed that the incident light should be parallel.
However, when comparing my experimental images with the interference patterns generated from the spherical object model, I noticed significant differences, especially when the defocus plane is close to focus.

(These are the parameters I used in the model calculation, which match my experimental parameters)
sphere = Sphere(n=1.59, r=1.55, center=(7.68471, 8.03803, 4.0))
medium_index = 1.33
illum_wavelen = 0.610
detector = hp.detector_grid(shape=(180, 180), spacing=0.088333)
holo = calc_holo(detector, sphere, medium_index, illum_wavelen,
illum_polarization=(1,0), theory='auto')

I noticed that lens effects might be involved, so I also tried using theory='MieLens', but the aforementioned issues still persist.
I'm quite puzzled and would like to ask what might be causing these differences?

P.S.: In my experimental setup, I'm using LED with color filters instead of a laser; also, the light source has no polarization properties, but for simplification in the simulation, I used x-direction polarization (I assumed that for spherical objects, polarization would only affect contrast?); I also haven't yet considered other aberrations in the optical system. Could you please provide some guidance?
Below are the simulated and experimental images.

<img width="520" alt="38adf58f63a340f9be07e9ebd628515f-1730832305" src="https://github.com/user-attachments/assets/a8c00871-d20e-4989-a504-e77ff0e72e11">
<img width="518" alt="a8f894356c024950a13e82307ff2f259-1730832347" src="https://github.com/user-attachments/assets/fb2eff56-38c4-4565-97dc-ea3e09933714">
