### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#47]
The following is a non-exhaustive list of issues with doc impacts
#10
#14
#31
#32
#42
#43
#45
#46

**Comment by barkls** [comment]
Aaron has requested a developer tutorial about how to add a scattering model.

**Comment by barkls** [comment]
Aaron has requested a convenient summary of all the small helper functions built into holopy to prevent everyone rewriting them individually. Things like averaging, centerfinding spring to mind.

**Comment by vnmanoharan** [comment]
We should add a section to the manual that is targeted to developers.  The helper functions should have docstrings -- if not, we should add them so that they show up in the auto-generated reference manual.  It might make sense to add an appendix to the user manual that discusses them.

**Comment by barkls** [comment]
The front-matter of HoloPy also needs updating - quick summary of what it is, references, funding sources, etc...

**Comment by barkls** [comment]
dev guide topics
1) how to add a scattering model
2) how to add an inference model (and mention this in inference page)
3) xarray rationale - how information is stored in xarray objects - 'flat' vs 'point', saving xarrays in attrs,

**Comment by barkls** [comment]
Fixed by # 184. I went through the list of all things mentioned in this thread to make sure they are addressed. Any outstanding docs issues (mainly additions) have their own issues at this point.
