### ISSUE TITLE
Rethink saving to file

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#78]
hp.save()
-defaults to saving any holopyobject as hdf5
-option to save to yaml if preferred

hp.save_image()
-saves Image object to image file
-saves metadata if compatible format
-options to control contrast range, discretization

**Comment by barkls** [comment]
current status: 
hp.save_image() works
hp.save() only does yaml and tif

**Comment by tdimiduk** [comment]
hp.save now saves anything xarray derived (so anything with potentially large amounts of array data) as hdf5.
