### ISSUE TITLE
Rethink fitting in holopy

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#86]
@vnmanoharan said: Should we get rid of the OpenOpt code? I don't think it is widely used, and if we're going to work on the fitting infrastructure, I'd rather it be based on lmfit.

**Comment by barkls** [comment]
For most applications, inference will be preferable over fitting. Fitting might still be advantageous in situations where users have a very good initial guess and want to be fast. With that in mind, I think we should prioritize speed when choosing how to fit.

**Comment by vnmanoharan** [comment]
There are two issues here:
1) should we get rid of the code that relies on OpenOpt?
2) should we rework the fitting infrastructure?

The OpenOpt code was added to allow people to use other minimization algorithms besides Levenberg-Marquardt (LM).  But in practice, LM is faster than most of the optimizers in OpenOpt.  And I don't know of any cases where anyone has used the OpenOpt minimizers for published analyses.  So I don't think it would hurt to get rid of any code that depends on OpenOpt.

The second issue is whether we should rework the fitting framework.  At this point I would rather keep the LM framework and discard OpenOpt.

**Comment by tdimiduk** [comment]
On 1), yes I think we should get rid of the OpenOpt code. I was never that impressed with the other minimizers when I was testing it. We can get rid of that code without any other rework on fitting, it is completely modular. 

On 2). I may need to poke fitting a little as part of the xarray conversion, and I might do some refactoring to share more code with inference as I actually put together an interface for the inference code (for #43). Beyond that, I am at the moment leaning against more substantial reworks of fitting just from a time perspective.

**Comment by barkls** [comment]
OpenOpt removed.
