### ISSUE TITLE
Conversion Tools for old file formats

### ISSUE THREAD

**Issue by tdimiduk** [manoharan-lab/holopy#89]
As discussed in #45 we are going to fork off readers for old formats (holopy yaml, older hdf5 files) into a separate repo.

I propose a name like holopy-legacy-reader, comment if you prefer something else.

My plan is that the legacy-reader will depend on modern HoloPy (as currently embodied in my xarray branch) for writing new style netcdf/hdf5 files but will contain the legacy code needed to read older files.

**Comment by barkls** [comment]
this sounds good to me.

**Comment by tdimiduk** [comment]
I have an initial version of this up at:
https://github.com/manoharan-lab/holopy-legacy-reader
so I will close this issue, further discussion on this subject can move to issues on that repo
