### ISSUE TITLE
Test Data Repo

### ISSUE THREAD

**Issue by tdimiduk** [manoharan-lab/holopy#90]
We currently have machinery to test against full saves of holograms, fields, etc, but no good way to distribute that test data. We don't want to check in large binary files to the main holopy repository. I think it would work well to have a seperate holopy-test-golds repo (or propose another name) where we check in that data and a script to grab those files in the main holopy.

Might be worth having an option for our run_nose script that would call it if needed to test against the full data:
python run_nose.py --fetch-full-golds 
or something like that.

**Comment by barkls** [comment]
personally, I remain unconvinced that we need to compare against a gold consisting of an entire hologram. I think a subset of 1-10 pixels to high precision should be sufficient to confirm that the same calculation has occurred. On a (slightly) related note, I have switched to including jpeg instead of tiff for new example image files.

**Comment by vnmanoharan** [comment]
JPEG is lossy, so it can't be used for tests.  But I'm not sure what you mean by "example image files."

**Comment by vnmanoharan** [comment]
Also, storing the test data seems like a good use case for [git large file storage](https://git-lfs.github.com/).  I think we have at least 1 GB of LFS within the manoharan-lab organization.

**Comment by tdimiduk** [comment]
@barkls you are probably right that we don't need to compare to entire holograms. However, I am getting a failure on an intensity test that compares to 4 selected values, and am not sure how big of a problem it is, it would be much more reassuring to know that things still matched for some conditions that resembled real usage, rather that just some selected points.

**Comment by tdimiduk** [comment]
@vnmanoharan should I check the full golds directly into the main repo with lfs? Or still make  a separate repo for them and use lfs there.

**Comment by vnmanoharan** [comment]
Although I did suggest using LFS, I actually have no idea how it works or what the best way to do things is. So whatever you think is best.

**Comment by tdimiduk** [comment]
From looking through the lfs description, it looks like it is probably fine to just use the main repository and will be simpler. The files are only a few MB, so not a big deal to download them with the repo, and using git lfs will avoid bloating up the repo if we revise them.

**Comment by tdimiduk** [comment]
I have added hdf5 files to my xarray branch (PR #91) with lfs, and it looks like it should work just fine. I think people who want do download the actual files will need to install git lfs, but if you don't install it you will just get little placeholder files, we may need to change the test functions to not error out when they see the lfs placeholders

**Comment by barkls** [comment]
maybe users who don't have git lfs can compare against a subset of pixels to get the best of both worlds.

**Comment by tdimiduk** [comment]
Currently what it is configured to do is check the max, min and mean values I think (which are stored in yaml files that are stored in the repository). You could switch it over if you think a subset of the pixels is a better thing to check.

@barkls Can you confirm if the tests choke on the lfs placeholder files? It is probably easier for you to check if you haven't installed it yet than for me to try to figure out uninstalling or simulating uninstalling. Once you confirm that is ok or fix it, please close this issue
